name: linter for python
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Pylint for python programs
      run: |
        find . -name '*.py' -exec pylint {} \;
    - name: Evaluation
      run: |
        N=$(find . -name '*.py' -exec pylint {} \; | sed -n '/^Your code has been rated at/p' | head -1 | tr -cd '0-9')
        N=$(expr $N / 100)
        git pull
        echo "Проверка кода написанного на языке python с помощью линкера pylint\n  Проверку проходят программы, балл в pylint которых больше 7.00\n  Результаты проверки на последнего пуша :[![link](https://github.com/andrey-andreu/linux-git1/actions/workflows/linter.yml/badge.svg)](https://github.com/andrey-andreu/linux-git1/actions/workflows/linter.yml)\n  Score: $N" >> README.md
        git commit -m "added the results" README.md
        git push
        if [ $N < 7000 ]; then
          exit 1
        fi
        
        
