name: linter for python
on:
  push:
    paths:
    - '**.py'
  status: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Results of pylint
      run: |
        find ./project2 -name '*.py' -exec pylint {} \;
    - name: Evaluation
      run: |
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git config user.name "${{ github.actor }}"
        cd project2
        file_n=$(find . -type f -mmin -3 | head -1)
        echo $file
        N=$(pylint $file_n | sed -n '/^Your code has been rated at/p' | head -1 | tr -cd '0-9')
        echo $N
        N=$(expr $N / 10000000000)
        N1=$(expr $N / 100)
        N2=$(expr $N % 100)
        git pull
        cd project2
        echo "Проверка кода написанного на языке python с помощью линкера pylint  
        Проверку проходят программы, балл в pylint которых больше 6.00  
          
        Результаты проверки последнего файла с расширением .py   
        [![link](https://github.com/andrey-andreu/linux-git1/actions/workflows/linter.yml/badge.svg)](https://github.com/andrey-andreu/linux-git1/actions/workflows/linter.yml)  
        Оценка pylint: $N1.$N2" > README.md
        git commit -m "added the results" README.md
        git push
        border=6
        if [ "$N1" -lt "$border" ]; then
          exit 1
        fi
        
        
