name: linter for python
on:
  push:
    paths:
    - '**.py'
  status: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Pylint for python programs
      run: |
        find . -name '*.py' -exec pylint {} \;
    - name: Evaluation
      run: |
        N=$(find . -name '*.py' -exec pylint {} \; | sed -n '/^Your code has been rated at/p' | head -1 | tr -cd '0-9')
        N=$(expr $N / 100)
        echo $N
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git config user.name "${{ github.actor }}"
        REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git pull
        echo "Проверка кода написанного на языке python с помощью линкера pylint
        Проверку проходят программы, балл в pylint которых больше 7.00
        Результаты проверки на последнего пуша :[![link](https://github.com/andrey-andreu/linux-git1/actions/workflows/linter.yml/badge.svg)](https://github.com/andrey-andreu/linux-git1/actions/workflows/linter.yml)
        Score: $N" > README.md
        git commit -m "added the results" README.md
        git push ${REMOTE}
        if [ $N < 7000 ]; then
          exit 1
        fi
        
        
