name: linter for python
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: pylint for python programs
      run: |
        find . -name '*.py' -exec pylint {} \ | sed -n '/^Your code has been rated at/p' | head -1
        
