name: linter for python
on:
  push:
    paths:
      - '*.py'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: pylint for python programs
      run: |
        find . -name '*.py' -exec pylint {} \;
    - name: Evaluation
      run: |
        N=$(find . -name '*.py' -exec pylint {} \; | sed -n '/^Your code has been rated at/p' | head -1 | tr -cd '0-9')
        N=$(expr $N / 100)
        if [ $N < 7000 ]; then
          exit 1
        fi
        
        
